### ISSUE TITLE
check_by_mask

### ISSUE THREAD

**Issue by aterpstra** [dennissergeev/octant#23]
Suggestion: generalize function by adding 'l_mask' value to parameter-list, so that one can use not only landmask, but any field + set a threshold value

Note on current 'l_mask==1' setting: ERA5 has such high-res that lots of lsm-values are <1.0, this results in keeping too many tracks over land.
For example see figs: 
(1.) no filtering (3000+ tracks) 
(2.) filtering with 'l_mask==1, rad=100.' (~1000 tracks, what's this stuff over Europe doing there??)
(3.) filtering with 'l_mask>0.5, rad=100.' (~400 tracks: this looks more like it :)

![image](https://user-images.githubusercontent.com/4747419/51559622-4b51b480-1e7a-11e9-8b74-c2bbe415aec6.png)
![image](https://user-images.githubusercontent.com/4747419/51559631-50aeff00-1e7a-11e9-96e5-cc8d55b5c467.png)
![image](https://user-images.githubusercontent.com/4747419/51559635-54428600-1e7a-11e9-94fc-162bba4a91f1.png)

**Comment by dennissergeev** [comment]
Good call. Added by d08682660bcb551b43ffb1c87079769d16f2b236
