### ISSUE TITLE
classify() for 'independent' categorization

### ISSUE THREAD

**Issue by aterpstra** [dennissergeev/octant#24]
It seems like every track in TrackRun can only be assigned 1 category (but maybe I am wrong??), as in  TR.data.loc[4, "cat"] has only one category assigned. 

This is problematic if one uses classify() with inclusive=False as categorization is not implemented 'exclusive', in other words: tracks cannot be members of several categories. For example: if a track has a genesis-close-to-sea-ice and a genesis-during-cao-conditions, than it will be assigned to either category depending on the order of the conditions during the call to classify(). 

Maybe this is just due to my limited pythonian skils, and is it indeed possible to assign multiple categories to one track?? If not than the 'inclusive' feature in classify is kinda misleading if 'False', ie. used as 'independent' categorization.

**Comment by dennissergeev** [comment]
Thanks for raising this issue, I agree that categorisation is not polished yet.
I can see how `inclusive=True` can be misleading if you want to assign multiple categories to a single track.

I will try to implement multi-categories feature, but for now you can try to emulate that with doing something like
```python
conds = [
    ('genesis-close-to-sea-ice', [func0]),
    ('genesis-during-cao', [func1]),
    ('genesis-close-to-sea-ice-and-during-cao', [func0, func1]),
]

trackrun.classify(conds, inclusive=False)
```
Does this make sense?

**Comment by aterpstra** [comment]
Yup, makes sense. This solution can become slightly confusing if not being very careful when working with multiple categories (not only 2 as in example but say 10 categories) as you have to add the intersects to the solo-conditions if you wanna consider all tracks in one category, besides it's getting computational expensive. 

My current solution is making several copies of same TrackRun and individually classify with only single condition, than use something like np.intersect1d to find 'shared' tracks. Works fine, though multi-categorization would be wonderful addition for the future :)
